Add vxlan tunnel support (#72)
Added support for inter-AP vxlan tunnels - with a few dependency enhancements

A new component, the NetreachApNetworkManager, which contains all the 
 logic for managing the inter-AP tunnels. In coordination with the NetreachAdapter
 the NetreachApNetworkManager sets up and tears down per-Service vxlan
 tunnels between APs to ensure that devices connected to the same NetReach
 Service/micronet are able to communicate over a backhaul network.

The following config variable are added:

MICRONETS_GATEWAY_MAC_ADDR

 This can be set explicitly or the MICRONETS_OVS_BRIDGE mac address
 will be used instead to route packets for the gateway MAC directly
 upstream. If unset the MAC address of MICRONETS_OVS_BRIDGE 
 will be used.

MICRONETS_GATEWAY_NETMASK (e.g. "10.0.0.1/255.0.0.255")

 The netmask that identifies all Micronet gateway addresses. Used to 
 generate rules that will route traffic to/from the gateway for each Micronet
 subnet.

NETREACH_ADAPTER_VXLAN_PEER_INAME_PREFIX (e.g. "nap.")

 This specifies the prefix used for tunnel interface names.

NETREACH_ADAPTER_VXLAN_PEER_INAME_FORMAT (e.g. "nap.{short_ap_id}.{vlan:x}")

 This determines the pattern used to construct tunnel interface names. 
 Note that the pattern must start with NETREACH_ADAPTER_VXLAN_PEER_INAME_PREFIX.

NETREACH_ADAPTER_VXLAN_NET_BRIDGE (e.g. "brhapd")

 The OVS bridge that the vxlan interfaces should be connected to and  
 OVS flows can be applied to.

NETREACH_ADAPTER_VXLAN_NET_MICRONETS_PORT  (e.g. "hapd-tr-patch")

 The port on NETREACH_ADAPTER_VXLAN_NET_BRIDGE that is connected
 to the Micronets OVS bridge.

NETREACH_ADAPTER_VXLAN_NET_HOSTAPD_PORT (e.g. "haport-sw")

 The port on NETREACH_ADAPTER_VXLAN_NET_BRIDGE that is connected 
 to hostapd's VLAN-tagged interface/bridge.

NETREACH_ADAPTER_VXLAN_LIST_PORTS (e.g. "/usr/bin/ovs-vsctl list-ports {vxlan_net_bridge}" )

 The command to be executed to list all the OVS port names for the given 
 OVS bridge (one port per line) with {vxlan_net_bridge} replaced with 
 NETREACH_ADAPTER_VXLAN_NET_BRIDGE.

NETREACH_ADAPTER_VXLAN_CONNECT_CMD (e.g. "/usr/bin/ovs-vsctl add-port {vxlan_net_bridge} {vxlan_port_name} -- set interface {vxlan_port_name} type=vxlan options:remote_ip={remote_vxlan_host} options:key={vxlan_conn_key}")

 The command to be executed to connect an OVS tunnel to a remote IP. "{vxlan_net_bridge}"
 is replaced with NETREACH_ADAPTER_VXLAN_NET_BRIDGE. "{vxlan_port_name}" is
 replaced with the port name on NETREACH_ADAPTER_VXLAN_NET_BRIDGE. "{remote_vxlan_host}"
 is replaced with the address of the peer AP for the vxlan tunnel. And "{vxlan_conn_key}"
 is replaced with the vxlan ID for the tunnel.

   NETREACH_ADAPTER_VXLAN_DISCONNECT_CMD (e.g. "/usr/bin/ovs-vsctl del-port {vxlan_port_name}")

 The command to be executed to disconnect an OVS tunnel. "{vxlan_port_name}" is
 replaced with the port name on NETREACH_ADAPTER_VXLAN_NET_BRIDGE. 
 "{vxlan_port_name}" is  replaced with the port name on NETREACH_ADAPTER_VXLAN_NET_BRIDGE.

Successfully tested with a number of 4-AP 5-device 2-Service test cases.

diff --git a/micronets-gw-service/bin/status b/micronets-gw-service/bin/status
--- a/micronets-gw-service/bin/status
+++ b/micronets-gw-service/bin/status
@@ -2,11 +2,20 @@
 
 # set -x
 
-bridgename=brmn001
+if [ $# -eq 0 ]; then
+  bridgename="brmn001"
+elif [ $# -eq 1 ]; then
+  bridgename="$1"
+else
+  echo "Error: Only 1 parameter allowed (bridge name)"
+  exit 1
+fi
 
 shortname="${0##*/}"
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
+echo "---------------------------------------------------------------------------------------"
+echo "SHOWING STATUS FOR BRIDGE $bridgename"
 echo "---------------------------------------------------------------------------------------"
 ip address show dev $bridgename
 echo "---------------------------------------------------------------------------------------"
